// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sales_analysis.Context;

#nullable disable

namespace sales_analysis.Migrations
{
    [DbContext(typeof(SalesAnalysisContext))]
    [Migration("20230701045553_sales-analysis-v1.0")]
    partial class salesanalysisv10
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("sales_analysis.Entities.Location", b =>
                {
                    b.Property<int>("location_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("location_id"), 1L, 1);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("location_id");

                    b.ToTable("locations");
                });

            modelBuilder.Entity("sales_analysis.Entities.SalesRecord", b =>
                {
                    b.Property<int>("sales_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sales_id"), 1L, 1);

                    b.Property<int>("location_id")
                        .HasColumnType("int");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<string>("product_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("sales_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("total_sales_amount")
                        .HasColumnType("int");

                    b.Property<int>("total_units")
                        .HasColumnType("int");

                    b.HasKey("sales_id");

                    b.HasIndex("location_id");

                    b.ToTable("sales_records");
                });

            modelBuilder.Entity("sales_analysis.Entities.SalesRecord", b =>
                {
                    b.HasOne("sales_analysis.Entities.Location", "location")
                        .WithMany("records")
                        .HasForeignKey("location_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("location");
                });

            modelBuilder.Entity("sales_analysis.Entities.Location", b =>
                {
                    b.Navigation("records");
                });
#pragma warning restore 612, 618
        }
    }
}
