// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sales_analysis.Context;

#nullable disable

namespace sales_analysis.Migrations
{
    [DbContext(typeof(SalesAnalysisContext))]
    partial class SalesAnalysisContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("sales_analysis.Entities.Location", b =>
                {
                    b.Property<int>("location_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("location_id"), 1L, 1);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("location_id");

                    b.ToTable("locations");

                    b.HasData(
                        new
                        {
                            location_id = 1,
                            name = "Chennai"
                        },
                        new
                        {
                            location_id = 2,
                            name = "Delhi"
                        },
                        new
                        {
                            location_id = 3,
                            name = "Mumbai"
                        },
                        new
                        {
                            location_id = 4,
                            name = "Bengaluru"
                        },
                        new
                        {
                            location_id = 5,
                            name = "Hyderabad"
                        });
                });

            modelBuilder.Entity("sales_analysis.Entities.SalesRecord", b =>
                {
                    b.Property<int>("sales_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sales_id"), 1L, 1);

                    b.Property<int>("location_id")
                        .HasColumnType("int");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<string>("product_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("sales_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("total_sales_amount")
                        .HasColumnType("int");

                    b.Property<int>("total_units")
                        .HasColumnType("int");

                    b.HasKey("sales_id");

                    b.HasIndex("location_id");

                    b.ToTable("sales_records");

                    b.HasData(
                        new
                        {
                            sales_id = 1,
                            location_id = 1,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 80000,
                            total_units = 10
                        },
                        new
                        {
                            sales_id = 2,
                            location_id = 1,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 60000,
                            total_units = 10
                        },
                        new
                        {
                            sales_id = 3,
                            location_id = 1,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 90000,
                            total_units = 10
                        },
                        new
                        {
                            sales_id = 4,
                            location_id = 2,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 96000,
                            total_units = 12
                        },
                        new
                        {
                            sales_id = 5,
                            location_id = 2,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 180000,
                            total_units = 30
                        },
                        new
                        {
                            sales_id = 6,
                            location_id = 2,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 405000,
                            total_units = 45
                        },
                        new
                        {
                            sales_id = 7,
                            location_id = 3,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 120000,
                            total_units = 15
                        },
                        new
                        {
                            sales_id = 8,
                            location_id = 3,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 108000,
                            total_units = 18
                        },
                        new
                        {
                            sales_id = 9,
                            location_id = 3,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 72000,
                            total_units = 8
                        },
                        new
                        {
                            sales_id = 10,
                            location_id = 4,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 112000,
                            total_units = 14
                        },
                        new
                        {
                            sales_id = 11,
                            location_id = 4,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 120000,
                            total_units = 20
                        },
                        new
                        {
                            sales_id = 12,
                            location_id = 4,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 171000,
                            total_units = 19
                        },
                        new
                        {
                            sales_id = 13,
                            location_id = 5,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 176000,
                            total_units = 22
                        },
                        new
                        {
                            sales_id = 14,
                            location_id = 5,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 96000,
                            total_units = 16
                        },
                        new
                        {
                            sales_id = 15,
                            location_id = 5,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 207000,
                            total_units = 23
                        },
                        new
                        {
                            sales_id = 16,
                            location_id = 1,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 160000,
                            total_units = 20
                        },
                        new
                        {
                            sales_id = 17,
                            location_id = 1,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 180000,
                            total_units = 30
                        },
                        new
                        {
                            sales_id = 18,
                            location_id = 1,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 207000,
                            total_units = 23
                        },
                        new
                        {
                            sales_id = 19,
                            location_id = 2,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 112000,
                            total_units = 14
                        },
                        new
                        {
                            sales_id = 20,
                            location_id = 2,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 204000,
                            total_units = 34
                        },
                        new
                        {
                            sales_id = 21,
                            location_id = 2,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 504000,
                            total_units = 56
                        },
                        new
                        {
                            sales_id = 22,
                            location_id = 3,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 208000,
                            total_units = 26
                        },
                        new
                        {
                            sales_id = 23,
                            location_id = 3,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 198000,
                            total_units = 33
                        },
                        new
                        {
                            sales_id = 24,
                            location_id = 3,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 189000,
                            total_units = 21
                        },
                        new
                        {
                            sales_id = 25,
                            location_id = 4,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 240000,
                            total_units = 30
                        },
                        new
                        {
                            sales_id = 26,
                            location_id = 4,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 90000,
                            total_units = 15
                        },
                        new
                        {
                            sales_id = 27,
                            location_id = 4,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 162000,
                            total_units = 18
                        },
                        new
                        {
                            sales_id = 28,
                            location_id = 5,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 280000,
                            total_units = 35
                        },
                        new
                        {
                            sales_id = 29,
                            location_id = 5,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 108000,
                            total_units = 18
                        },
                        new
                        {
                            sales_id = 30,
                            location_id = 5,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 234000,
                            total_units = 26
                        },
                        new
                        {
                            sales_id = 31,
                            location_id = 1,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 360000,
                            total_units = 45
                        },
                        new
                        {
                            sales_id = 32,
                            location_id = 1,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 216000,
                            total_units = 36
                        },
                        new
                        {
                            sales_id = 33,
                            location_id = 1,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 702000,
                            total_units = 78
                        },
                        new
                        {
                            sales_id = 34,
                            location_id = 2,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 560000,
                            total_units = 70
                        },
                        new
                        {
                            sales_id = 35,
                            location_id = 2,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 402000,
                            total_units = 67
                        },
                        new
                        {
                            sales_id = 36,
                            location_id = 2,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 450000,
                            total_units = 50
                        },
                        new
                        {
                            sales_id = 37,
                            location_id = 3,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 400000,
                            total_units = 50
                        },
                        new
                        {
                            sales_id = 38,
                            location_id = 3,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 180000,
                            total_units = 30
                        },
                        new
                        {
                            sales_id = 39,
                            location_id = 3,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 630000,
                            total_units = 70
                        },
                        new
                        {
                            sales_id = 40,
                            location_id = 4,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 160000,
                            total_units = 20
                        },
                        new
                        {
                            sales_id = 41,
                            location_id = 4,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 78000,
                            total_units = 13
                        },
                        new
                        {
                            sales_id = 42,
                            location_id = 4,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 540000,
                            total_units = 60
                        },
                        new
                        {
                            sales_id = 43,
                            location_id = 5,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 264000,
                            total_units = 33
                        },
                        new
                        {
                            sales_id = 44,
                            location_id = 5,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 144000,
                            total_units = 24
                        },
                        new
                        {
                            sales_id = 45,
                            location_id = 5,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 153000,
                            total_units = 17
                        },
                        new
                        {
                            sales_id = 46,
                            location_id = 1,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 184000,
                            total_units = 23
                        },
                        new
                        {
                            sales_id = 47,
                            location_id = 1,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 72000,
                            total_units = 12
                        },
                        new
                        {
                            sales_id = 48,
                            location_id = 1,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 117000,
                            total_units = 13
                        },
                        new
                        {
                            sales_id = 49,
                            location_id = 2,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 800000,
                            total_units = 100
                        },
                        new
                        {
                            sales_id = 50,
                            location_id = 2,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 720000,
                            total_units = 120
                        },
                        new
                        {
                            sales_id = 51,
                            location_id = 2,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 387000,
                            total_units = 43
                        },
                        new
                        {
                            sales_id = 52,
                            location_id = 3,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 144000,
                            total_units = 18
                        },
                        new
                        {
                            sales_id = 53,
                            location_id = 3,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 102000,
                            total_units = 17
                        },
                        new
                        {
                            sales_id = 54,
                            location_id = 3,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 162000,
                            total_units = 18
                        },
                        new
                        {
                            sales_id = 55,
                            location_id = 4,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 176000,
                            total_units = 22
                        },
                        new
                        {
                            sales_id = 56,
                            location_id = 4,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 150000,
                            total_units = 25
                        },
                        new
                        {
                            sales_id = 57,
                            location_id = 4,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 180000,
                            total_units = 20
                        },
                        new
                        {
                            sales_id = 58,
                            location_id = 5,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 200000,
                            total_units = 25
                        },
                        new
                        {
                            sales_id = 59,
                            location_id = 5,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 210000,
                            total_units = 35
                        },
                        new
                        {
                            sales_id = 60,
                            location_id = 5,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 171000,
                            total_units = 19
                        },
                        new
                        {
                            sales_id = 61,
                            location_id = 1,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 32000,
                            total_units = 4
                        },
                        new
                        {
                            sales_id = 62,
                            location_id = 1,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 30000,
                            total_units = 5
                        },
                        new
                        {
                            sales_id = 63,
                            location_id = 1,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 54000,
                            total_units = 6
                        },
                        new
                        {
                            sales_id = 64,
                            location_id = 2,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 80000,
                            total_units = 10
                        },
                        new
                        {
                            sales_id = 65,
                            location_id = 2,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 192000,
                            total_units = 32
                        },
                        new
                        {
                            sales_id = 66,
                            location_id = 2,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 207000,
                            total_units = 23
                        },
                        new
                        {
                            sales_id = 67,
                            location_id = 3,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 64000,
                            total_units = 8
                        },
                        new
                        {
                            sales_id = 68,
                            location_id = 3,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 90000,
                            total_units = 15
                        },
                        new
                        {
                            sales_id = 69,
                            location_id = 3,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 144000,
                            total_units = 16
                        },
                        new
                        {
                            sales_id = 70,
                            location_id = 4,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 128000,
                            total_units = 16
                        },
                        new
                        {
                            sales_id = 71,
                            location_id = 4,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 120000,
                            total_units = 20
                        },
                        new
                        {
                            sales_id = 72,
                            location_id = 4,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 207000,
                            total_units = 23
                        },
                        new
                        {
                            sales_id = 73,
                            location_id = 5,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 184000,
                            total_units = 23
                        },
                        new
                        {
                            sales_id = 74,
                            location_id = 5,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 108000,
                            total_units = 18
                        },
                        new
                        {
                            sales_id = 75,
                            location_id = 5,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 324000,
                            total_units = 36
                        },
                        new
                        {
                            sales_id = 76,
                            location_id = 1,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 64000,
                            total_units = 8
                        },
                        new
                        {
                            sales_id = 77,
                            location_id = 1,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 54000,
                            total_units = 9
                        },
                        new
                        {
                            sales_id = 78,
                            location_id = 1,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 90000,
                            total_units = 10
                        },
                        new
                        {
                            sales_id = 79,
                            location_id = 2,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 432000,
                            total_units = 54
                        },
                        new
                        {
                            sales_id = 80,
                            location_id = 2,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 390000,
                            total_units = 65
                        },
                        new
                        {
                            sales_id = 81,
                            location_id = 2,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 207000,
                            total_units = 23
                        },
                        new
                        {
                            sales_id = 82,
                            location_id = 3,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 96000,
                            total_units = 12
                        },
                        new
                        {
                            sales_id = 83,
                            location_id = 3,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 138000,
                            total_units = 23
                        },
                        new
                        {
                            sales_id = 84,
                            location_id = 3,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 99000,
                            total_units = 11
                        },
                        new
                        {
                            sales_id = 85,
                            location_id = 4,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 160000,
                            total_units = 20
                        },
                        new
                        {
                            sales_id = 86,
                            location_id = 4,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 102000,
                            total_units = 17
                        },
                        new
                        {
                            sales_id = 87,
                            location_id = 4,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 225000,
                            total_units = 25
                        },
                        new
                        {
                            sales_id = 88,
                            location_id = 5,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 144000,
                            total_units = 18
                        },
                        new
                        {
                            sales_id = 89,
                            location_id = 5,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 150000,
                            total_units = 25
                        },
                        new
                        {
                            sales_id = 90,
                            location_id = 5,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 315000,
                            total_units = 35
                        },
                        new
                        {
                            sales_id = 91,
                            location_id = 1,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 360000,
                            total_units = 45
                        },
                        new
                        {
                            sales_id = 92,
                            location_id = 1,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 264000,
                            total_units = 44
                        },
                        new
                        {
                            sales_id = 93,
                            location_id = 1,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 54000,
                            total_units = 6
                        },
                        new
                        {
                            sales_id = 94,
                            location_id = 2,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 256000,
                            total_units = 32
                        },
                        new
                        {
                            sales_id = 95,
                            location_id = 2,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 126000,
                            total_units = 21
                        },
                        new
                        {
                            sales_id = 96,
                            location_id = 2,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 396000,
                            total_units = 44
                        },
                        new
                        {
                            sales_id = 97,
                            location_id = 3,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 328000,
                            total_units = 41
                        },
                        new
                        {
                            sales_id = 98,
                            location_id = 3,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 258000,
                            total_units = 43
                        },
                        new
                        {
                            sales_id = 99,
                            location_id = 3,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 63000,
                            total_units = 7
                        },
                        new
                        {
                            sales_id = 100,
                            location_id = 4,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 352000,
                            total_units = 44
                        },
                        new
                        {
                            sales_id = 101,
                            location_id = 4,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 150000,
                            total_units = 25
                        },
                        new
                        {
                            sales_id = 102,
                            location_id = 4,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 171000,
                            total_units = 19
                        },
                        new
                        {
                            sales_id = 103,
                            location_id = 5,
                            price = 8000,
                            product_name = "VA1",
                            sales_date = new DateTime(2023, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 320000,
                            total_units = 40
                        },
                        new
                        {
                            sales_id = 104,
                            location_id = 5,
                            price = 6000,
                            product_name = "VA2",
                            sales_date = new DateTime(2023, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 168000,
                            total_units = 28
                        },
                        new
                        {
                            sales_id = 105,
                            location_id = 5,
                            price = 9000,
                            product_name = "VA3",
                            sales_date = new DateTime(2023, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_sales_amount = 198000,
                            total_units = 22
                        });
                });

            modelBuilder.Entity("sales_analysis.Entities.SalesRecord", b =>
                {
                    b.HasOne("sales_analysis.Entities.Location", "location")
                        .WithMany("records")
                        .HasForeignKey("location_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("location");
                });

            modelBuilder.Entity("sales_analysis.Entities.Location", b =>
                {
                    b.Navigation("records");
                });
#pragma warning restore 612, 618
        }
    }
}
